---
title: 不合法的導向
image: ''
description: ''
keywords: ''
author: Opshell
createdAt: '2024-11-01'
categories:
tags:
editLink: true
isPublished: false
---
在 vue router 的 beforeEnter 中
有些時候會做一些驗證  驗證失敗要導向的行動

比如我們要取得會員資料

常見的做法是使用 `try catch`
```ts
beforeEnter: async (to) => {
    const memberStore = piniaStore.useMemberStore;
    const { memberState } = storeToRefs(memberStore);

    const memberId = Number(to.params?.member_id) || 0;
    // [-]沒選定會員就去導向會員列表
    if (!memberId) {
        return { name: 'MemberList', params: { page: 1 } };
    }

    // [-]當前會員資料同這個會員的時候 直接導向
    if (memberState.value.member_id === memberId) { return; }

    // [-]上述條件不符合時重新取得會員資料
    try {
        const result = await sendRequest(`/api/present_pat/simpledata/${MemberId}`);
        if (!result?.status) { throw new Error('取得病患資料失敗'); }

        MemberStore.updateMember(result.data);
    } catch (_error) {
        return { name: 'MemberList', params: { page: 1 } };
    }
};
```
然後他噴錯誤了
```
vue-router.mjs:962  Uncaught (in promise) Error: Navigation aborted from "/" to "/Member-list/1" via a navigation guard.
```

```ts
beforeEnter: async (to) => {
    const memberStore = piniaStore.useMemberStore;
    const { memberState } = storeToRefs(memberStore);

    const memberId = Number(to.params?.member_id) || 0;
    // [-]沒選定會員就去導向會員列表
    if (!memberId) {
        return { name: 'MemberList', params: { page: 1 } };
    }

    // [-]當前會員資料同這個會員的時候 直接導向
    if (memberState.value.member_id === memberId) { return; }

    // [-]上述條件不符合時重新取得會員資料
    const newMemberFlag = await sendRequest(`/api/mamber/${memberId}`).then((res) => {
        if (!res?.status) { throw new Error('取得會員資料錯誤!'); }

        memberStore.updateMember(res.data);
    }).catch((error) => {
        console.error('取得會員資料錯誤', error);
        return false;
    });

    if (!newMemberFlag) { return { name: 'MemberList', params: { page: 1 } }; }
};
```




const newMemberFlag = await sendRequest(`/api/present_pat/simpledata/${MemberId}`).then((res) => {
                if (!res?.status) { throw new Error('取得病患資料錯誤!'); }

                MemberStore.updateMember(res.data);
            }).catch((error) => {
                console.error('取得病患資料錯誤', error);

                return false;
            });

            if (!newMemberFlag) {
                return { name: 'MemberList', params: { page: 1 } };
            }



            let flag = true;
            try {
                const result = await sendRequest(`/api/present_pat/simpledata/${patientId}`);
                if (!result?.status) { throw new Error('取得病患資料失敗'); }

                patientStore.updatePatient(result.data);
            } catch (_error) {
                console.error(_error);
                flag = false;
            }

            if (!flag) {
                return { name: 'PatientList' };
            }
